In [1]:
#import libs
import h5py
import numpy as np 
from matplotlib import pyplot as plt
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
import csv
import pandas as pd

In [2]:
#Create Model class
class MultiDigitModel:
    
    def __init__(self):
        #first digit model
        self.model_1 = Sequential()
        self.model_1.add(Conv2D(16, kernel_size=(5,5), activation='relu', input_shape=(64,64,1)))
        self.model_1.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_1.add(Conv2D(32, (5, 5), activation='relu'))
        self.model_1.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_1.add(Conv2D(64, (3, 3), activation='relu'))
        self.model_1.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_1.add(Dropout(0.25))
        self.model_1.add(Flatten())
        self.model_1.add(Dense(128, activation="relu"))
        self.model_1.add(Dropout(0.5))
        self.model_1.add(Dense(10,activation="softmax"))
        #second digit model
        self.model_2 = Sequential()
        self.model_2.add(Conv2D(16, kernel_size=(5,5), activation='relu', input_shape=(64,64,1)))
        self.model_2.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_2.add(Conv2D(32, (5, 5), activation='relu'))
        self.model_2.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_2.add(Conv2D(64, (3, 3), activation='relu'))
        self.model_2.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_2.add(Dropout(0.25))
        self.model_2.add(Flatten())
        self.model_2.add(Dense(128, activation="relu"))
        self.model_2.add(Dropout(0.5))
        self.model_2.add(Dense(11,activation="softmax"))
        #third digit model
        self.model_3 = Sequential()
        self.model_3.add(Conv2D(16, kernel_size=(5,5), activation='relu', input_shape=(64,64,1)))
        self.model_3.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_3.add(Conv2D(32, (5, 5), activation='relu'))
        self.model_3.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_3.add(Conv2D(64, (3, 3), activation='relu'))
        self.model_3.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_3.add(Dropout(0.25))
        self.model_3.add(Flatten())
        self.model_3.add(Dense(128, activation="relu"))
        self.model_3.add(Dropout(0.55))
        self.model_3.add(Dense(11,activation="softmax"))
        #fourth digit model
        self.model_4 = Sequential()
        self.model_4.add(Conv2D(16, kernel_size=(5,5), activation='relu',  input_shape=(64,64,1)))
        self.model_4.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_4.add(Conv2D(32, (5, 5), activation='relu'))
        self.model_4.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_4.add(Conv2D(64, (3, 3), activation='relu'))
        self.model_4.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_4.add(Dropout(0.25))
        self.model_4.add(Flatten())
        self.model_4.add(Dense(128, activation="relu"))
        self.model_4.add(Dropout(0.6))
        self.model_4.add(Dense(11,activation="softmax"))
        #fifth digit model
        self.model_5 = Sequential()
        self.model_5.add(Conv2D(16, kernel_size=(5,5), activation='relu',  input_shape=(64,64,1)))
        self.model_5.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_5.add(Conv2D(32, (5, 5), activation='relu'))
        self.model_5.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_5.add(Conv2D(64, (3, 3), activation='relu'))
        self.model_5.add(MaxPooling2D(pool_size=(2, 2)))
        self.model_5.add(Dropout(0.25))
        self.model_5.add(Flatten())
        self.model_5.add(Dense(128, activation="relu"))
        self.model_5.add(Dropout(0.6))
        self.model_5.add(Dense(11,activation="softmax"))

    
    
    #Fit data function
    def fit(self,X_train,y_train, num_epoch = 15):
        X_train = X_train.astype('float32')
        X_train /= 255
        history = []
        #opt = keras.optimizers.Adam(learning_rate=0.001)
        print("===========================================================")
        print("First Model")
        print("===========================================================")
        self.model_1.compile(loss='sparse_categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
        hist1 = self.model_1.fit(x=X_train,y=y_train[:,0], epochs=num_epoch, validation_split = 0.1)
        history.append(hist1.history.get('accuracy')[-1])
        print("===========================================================")
        print("Second Model")
        print("===========================================================")
        self.model_2.compile(loss='sparse_categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
        hist2 = self.model_2.fit(x=X_train,y=y_train[:,1], epochs=num_epoch, validation_split = 0.1)
        history.append(hist2.history.get('accuracy')[-1])
        print("===========================================================")
        print("Third Model")
        print("===========================================================")
        self.model_3.compile(loss='sparse_categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
        hist3 = self.model_3.fit(x=X_train,y=y_train[:,2], epochs=num_epoch, validation_split = 0.1)
        history.append(hist3.history.get('accuracy')[-1])
        print("===========================================================")
        print("Fourth Model")
        print("===========================================================")
        self.model_4.compile(loss='sparse_categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
        hist4 = self.model_4.fit(x=X_train,y=y_train[:,3], epochs=num_epoch, validation_split = 0.1)
        history.append(hist4.history.get('accuracy')[-1])
        print("===========================================================")
        print("Fifth Model")
        print("===========================================================")
        self.model_5.compile(loss='sparse_categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
        hist5 = self.model_5.fit(x=X_train,y=y_train[:,4], epochs=num_epoch, validation_split = 0.1)
        history.append(hist5.history.get('accuracy')[-1])
        return history
    
    #Evaluate model, take the prodaut and average of the 5 models
    def evaluate(self,X_test,y_test):
        X_test= X_test.astype('float32')
        X_test /= 255
        score1 = self.model_1.evaluate(X_test, y_test[:,0])
        print("The first digit score:", score1)
        score2 = self.model_2.evaluate(X_test, y_test[:,1])
        print("The second digit score:", score2)
        score3 = self.model_3.evaluate(X_test, y_test[:,2])
        print("The third digit score:", score3)
        score4 = self.model_4.evaluate(X_test, y_test[:,3])
        print("The fourth digit score:", score4)
        score5 = self.model_5.evaluate(X_test, y_test[:,4])
        print("The fifth digit score:", score5)
        average = [(score1[0]+score2[0]+score3[0]+score4[0]+score5[0])/5.0, score1[1]*score2[1]*score3[1]*score4[1]*score5[1]]
        print("The average score:", average)
        return average
    
    #Predit data function   
    def predict(self,X_test):
        X_test = X_test.astype('float32')
        X_test /= 255
        digit1 = self.model_1.predict(X_test)
        digit1 = [x.argmax() for x in digit1]
        digit2 = self.model_2.predict(X_test)
        digit2 = [x.argmax() for x in digit2]
        digit3 = self.model_3.predict(X_test)
        digit3 = [x.argmax() for x in digit3]
        digit4 = self.model_4.predict(X_test)
        digit4 = [x.argmax() for x in digit4]
        digit5 = self.model_5.predict(X_test)
        digit5 = [x.argmax() for x in digit5]
        result = [str(digit1[i])+str(digit2[i])+str(digit3[i])+str(digit4[i])+str(digit5[i]) for i in range(len(digit1))]
        return result

In [3]:
#Preprocess
f1 = h5py.File('synthetic.h5', 'r+')
#print(list(f1.keys()))
X_train = f1['train_dataset']
X_test = f1['test_dataset']
Y_train = f1['train_labels']
dxtrain= np.array(X_train[()])
dxtest= np.array(X_test[()])
dytrain= np.array(Y_train[()])
x_train, x_test, y_train, y_test = train_test_split(dxtrain,dytrain, test_size=0.2, random_state=42)
input_shape = (64, 64, 1)
#if you want to see a image
#plt.imshow(dxtrain[image_index].reshape(64, 64)) 
#if you want ot check data shape
# print (dxtrain.shape)
# print (dytrain.shape)
# print (dxtest.shape)

In [4]:
#Fit data and Evaluate
Model = MultiDigitModel()
rowNum=0
#create a 5 column by 3 row array, where each row stores the number of epoc
#goes from epochs = 5 , 10, 15, 20, 25, 30
epochArray = np.zeros(shape=(6,3))
i=5
rowNum = 0
while i<=30:
    hist = Model.fit(x_train, y_train, 5)  #change to 5 later
    acc = Model.evaluate(x_test, y_test)
    epochArray[rowNum, 0] = i
    tmp = 1.0
    for x in hist:
        tmp *= x
    epochArray[rowNum, 1] = tmp
    epochArray[rowNum, 2] = acc[1]
    rowNum += 1
    i += 5



    

First Model
Train on 40320 samples, validate on 4480 samples
Epoch 1/5
40320/40320 [==============================] - 99s 2ms/sample - loss: 0.8619 - accuracy: 0.6991 - val_loss: 0.2682 - val_accuracy: 0.9221
Epoch 2/5
40320/40320 [==============================] - 89s 2ms/sample - loss: 0.2589 - accuracy: 0.9247 - val_loss: 0.1675 - val_accuracy: 0.9531
Epoch 3/5
40320/40320 [==============================] - 98s 2ms/sample - loss: 0.1759 - accuracy: 0.9475 - val_loss: 0.1212 - val_accuracy: 0.9634
Epoch 4/5
40320/40320 [==============================] - 92s 2ms/sample - loss: 0.1420 - accuracy: 0.9579 - val_loss: 0.1106 - val_accuracy: 0.9681
Epoch 5/5
40320/40320 [==============================] - 98s 2ms/sample - loss: 0.1214 - accuracy: 0.9640 - val_loss: 0.0996 - val_accuracy: 0.9728
Second Model
Train on 40320 samples, validate on 4480 samples
Epoch 1/5
40320/40320 [==============================] - 96s 2ms/sample - loss: 1.2049 - accuracy: 0.5628 - val_loss: 0.4516 - val_accura

40320/40320 [==============================] - 90s 2ms/sample - loss: 0.1183 - accuracy: 0.9649 - val_loss: 0.0736 - val_accuracy: 0.9801
Epoch 2/5
40320/40320 [==============================] - 90s 2ms/sample - loss: 0.1027 - accuracy: 0.9696 - val_loss: 0.0782 - val_accuracy: 0.9801
Epoch 3/5
40320/40320 [==============================] - 91s 2ms/sample - loss: 0.0884 - accuracy: 0.9746 - val_loss: 0.0713 - val_accuracy: 0.9808
Epoch 4/5
40320/40320 [==============================] - 89s 2ms/sample - loss: 0.0814 - accuracy: 0.9765 - val_loss: 0.0780 - val_accuracy: 0.9806
Epoch 5/5
40320/40320 [==============================] - 89s 2ms/sample - loss: 0.0718 - accuracy: 0.9788 - val_loss: 0.0883 - val_accuracy: 0.9806
Fourth Model
Train on 40320 samples, validate on 4480 samples
Epoch 1/5
40320/40320 [==============================] - 91s 2ms/sample - loss: 0.0832 - accuracy: 0.9756 - val_loss: 0.0525 - val_accuracy: 0.9842
Epoch 2/5
40320/40320 [==============================] - 89s

40320/40320 [==============================] - 102s 3ms/sample - loss: 0.0423 - accuracy: 0.9873 - val_loss: 0.0930 - val_accuracy: 0.9846
Epoch 2/5
40320/40320 [==============================] - 91s 2ms/sample - loss: 0.0424 - accuracy: 0.9876 - val_loss: 0.1142 - val_accuracy: 0.9821
Epoch 3/5
40320/40320 [==============================] - 92s 2ms/sample - loss: 0.0374 - accuracy: 0.9887 - val_loss: 0.0861 - val_accuracy: 0.9848
Epoch 4/5
40320/40320 [==============================] - 93s 2ms/sample - loss: 0.0405 - accuracy: 0.9878 - val_loss: 0.0752 - val_accuracy: 0.9859
Epoch 5/5
40320/40320 [==============================] - 93s 2ms/sample - loss: 0.0373 - accuracy: 0.9884 - val_loss: 0.0793 - val_accuracy: 0.9877
Fourth Model
Train on 40320 samples, validate on 4480 samples
Epoch 1/5
40320/40320 [==============================] - 99s 2ms/sample - loss: 0.0325 - accuracy: 0.9903 - val_loss: 0.0426 - val_accuracy: 0.9895
Epoch 2/5
40320/40320 [==============================] - 92

In [5]:
print(epochArray)

[[ 5.          0.83774351  0.89325005]
 [10.          0.9129556   0.91929376]
 [15.          0.93904939  0.92404121]
 [20.          0.94942778  0.93215072]
 [25.          0.95448622  0.93494296]
 [30.          0.95802803  0.93308008]]


In [ ]:
#generate csv file
submission = pd.DataFrame({'Id':range(len(result)),'Label':result})

#first 5 lines of the table
submission.head()

filename = 'sample.csv'
submission.to_csv(filename,index=False)